Excels/Excels/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Exstore.urls', namespace='app')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Excels/Exstore/urls.py
from django.conf.urls import url
from .views import UserDataList, save_to_db, LogView

urlpatterns = [
    url(r'^$', UserDataList.as_view(), name='list'),
    url(r'^upload/$', save_to_db, name='upload'),
    url(r'^logs/$', LogView.as_view(), name='logs'),
]

Excels/Exstore/models.py
from django.db import models


class UserData(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField()
    gender = models.CharField(default='Male', choices=GENDER_CHOICES, max_length=6)
    address = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'User Data'
        unique_together = (('first_name', 'last_name', 'age', 'gender', 'address',),)

    def __str__(self):
        return self.fullname()

    def fullname(self):
        return self.first_name + self.last_name

    # def unique_error_message(self, model_class, unique_check):
    #     if model_class == type(self) and unique_check == ('first_name', 'last_name', 'age', 'gender', 'address',):
    #         return 'Sorry this data already exists in the database'
    #     else:
    #         return super(UserData, self).unique_error_message(model_class, unique_check)


class Log(models.Model):
    LOG_ACTIONS = (
        ('file_upload', 'file_upload'),
    )
    action = models.CharField(max_length=20, default='file_upload', choices=LOG_ACTIONS, verbose_name= 'action')
    message = models.CharField(max_length=200, default='nothing')
    date = models.DateTimeField(auto_now_add=True, verbose_name='date')

    class Meta:
        verbose_name = 'Log'
        verbose_name_plural = 'Logs'

Excels/Exstore/forms.py
from django import forms


class Importer(forms.Form):
    file = forms.FileField()

Excels/Exstore/views.py
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.http import HttpResponseBadRequest, HttpResponseRedirect, HttpResponse
from django.views.generic import ListView
from django.template import RequestContext
import django_excel as excel
import pyexcel_xls
import pyexcel_xlsx
from .models import UserData, Log
from .forms import Importer
from djcelery import celery
from .tasks import *



class UserDataList(ListView):
    model = UserData
    queryset = UserData.objects.all()
    context_object_name = 'user_data'


class LogView(ListView):
    model = Log
    queryset = Log.objects.all()
    context_object_name = 'logs'


def save_to_db(request):
    if request.method == "POST":
        form = Importer(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            import_data.delay(file)
            file_name = request.FILES['file'].name
            new_log = Log(action='file_upload', message=file_name)
            new_log.save()
            return HttpResponseRedirect(reverse('app:list'))
        else:
            return HttpResponseBadRequest()
    else:
        form = Importer()
    return render_to_response('Exstore/upload_form.html', {'form': form}, context_instance=RequestContext(request))


def test_celery(request):
	result = tasks.sleeptask.delay(10)
	result_one = tasks.sleeptask.delay(10)
	result_two = tasks.sleeptask.delay(10)
	return HttpResponse(result.task_id)

Excels/Exstore/templates/Exstore/log_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<table>
    <thead>
    <th>S/N</th>
    <th>ACTION</th>
    <th>FILE NAME</th>
    <th>DATE</th>
    </thead>
    <tbody>

{% for log in logs %}
    <tr>
        <td>{{log.id}}</td>
        <td>{{log.action}}</td>
        <td>{{log.message}}</td>
        <td>{{log.date}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>



{% endblock %}

Excels/Exstore/templates/Exstore/upload_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
<center>
    <h4>Upload spreedsheet</h4>
    <form action="" enctype="multipart/form-data"  method="post" id="upload_form">
        <p>{{ form.as_p}}</p>
        {% csrf_token %}
        <input type="submit" value="Upload" id="input">
    </form>
</center>
{% endblock %}

Excels/Exstore/templates/Exstore/userdata_list.html
{% extends 'base.html' %}
{% load static %}
<h1>user's data</h1>


{% block content %}
<center>

<table>
  <thead>
  <tr >
    <th>First Name</th>
    <th>Last Name</th>
    <th>Age</th>
    <th>Gender</th>
    <th>Address</th>
  </tr>
  </thead>
  <tr>

    {% for user in user_data %}
    <td>{{user.first_name}}</td>
    <td>{{user.last_name}}</td>
    <td>{{user.age}}</td>
    <td>{{user.gender}}</td>
    <td>{{user.address}}</td>
  </tr>
  {% endfor %}
</table>
  </center>
{% endblock %}

Excels/templates/base.html
{% load static %}
{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" href="{% static 'Exstore/css/style.css' %}" />
{% endblock %}

<body>
<nav>
    <ul>
        <li><a href="{% url  'app:list' %}"><h2>Users</h2></a></li>
        <li><a href="{% url  'app:upload' %}"><h2>Upload</h2></a></li>
        <li><a href="{% url  'app:logs' %}"><h2>Logs</h2></a></li>
    </ul>
</nav>
{% block content %}
{% endblock %}
</body>